// Frontend copy of plan definitions for display in the Dashboard and Pricing UI.
// Backend logic lives in base44/shared/plans.js.

export const PLANS = {
  observer: {
    id: 'observer',
    name: 'Observer',
    price: 0,
    manifestation_energy: 0,
    narration_energy: 0,
    color: 'text-muted-foreground',
    badge: 'bg-muted/20 text-muted-foreground border-muted-foreground/30',
    features: [
      'Browse all 50 states + international tours',
      'View tour details, stops, maps, and text',
      'Save favorites',
    ],
  },
  explorer: {
    id: 'explorer',
    name: 'Explorer',
    manifestation_energy: 5,
    narration_energy: 300,
    monthly_price: 4.99,
    annual_price: 49.99,
    color: 'text-primary',
    badge: 'bg-primary/20 text-primary border-primary/40',
    features: [
      'Everything in Observer',
      'AI narration (~1 complete tour/month)',
      'Custom tour generation (1-2/month)',
      'All ranked tours unlocked',
      'Nearby + Abroad tours',
      'Evidence Journal (upload + track)',
      'Community Map access',
      'Leaderboard access',
      'Standard toolkit (8 tools)',
      'Aura Bundle purchases',
    ],
  },
  investigator: {
    id: 'investigator',
    name: 'Investigator',
    manifestation_energy: 15,
    narration_energy: 1000,
    monthly_price: 9.99,
    annual_price: 99.99,
    color: 'text-accent-foreground',
    badge: 'bg-accent/20 text-accent-foreground border-accent/40',
    features: [
      'Everything in Explorer',
      'AI narration for ~4 complete tours/month',
      'Custom tour generation (up to 5/month)',
      'Full toolkit (all 12 tools)',
      'Evidence Dashboard with analytics',
      'Aura Bundle purchases',
    ],
  },
  trailblazer: {
    id: 'trailblazer',
    name: 'Trailblazer',
    manifestation_energy: 25,
    narration_energy: 1200,
    one_time_price: 199.99,
    duration_years: 3,
    max_slots: 300,
    color: 'text-amber-400',
    badge: 'bg-amber-500/20 text-amber-400 border-amber-500/40',
    features: [
      'Everything in Investigator',
      'AI narration for ~5 complete tours/month',
      'Custom tour generation (up to 8/month)',
      'Exclusive Trailblazer badge',
      'Early access to new features',
      '3-year price lock guarantee',
      'Seasonal Aura Bundle discounts (20% off)',
      'Limited to 300 slots',
    ],
  },
};

export const AURA_BUNDLES = {
  flicker: {
    id: 'flicker',
    name: 'Flicker',
    energy: 100,
    price: 0.99,
    narration_pct: 0.8,
    manifestation_pct: 0.2,
    icon: '🕯️',
    desc: 'A small spark — 100 energy to top up',
  },
  apparition: {
    id: 'apparition',
    name: 'Apparition',
    energy: 400,
    price: 3.99,
    narration_pct: 0.8,
    manifestation_pct: 0.2,
    icon: '👻',
    desc: 'A steady presence — 400 energy',
  },
  haunting: {
    id: 'haunting',
    name: 'Haunting',
    energy: 1000,
    price: 9.99,
    narration_pct: 0.8,
    manifestation_pct: 0.2,
    icon: '🌫️',
    desc: 'A powerful surge — 1,000 energy',
  },
  spectral: {
    id: 'spectral',
    name: 'Spectral',
    energy: 2000,
    price: 17.99,
    narration_pct: 0.8,
    manifestation_pct: 0.2,
    icon: '✨',
    desc: 'Maximum energy — 2,000 energy',
  },
};

export const PLAN_ORDER = ['observer', 'explorer', 'investigator', 'trailblazer'];