// Frontend copy of plan definitions for display in the Dashboard and Pricing UI.
// Backend logic lives in base44/shared/plans.js.

export const PLANS = {
  observer: {
    id: 'observer',
    name: 'Observer',
    price: 0,
    manifestation_energy: 0,
    narration_energy: 0,
    color: 'text-muted-foreground',
    badge: 'bg-muted/20 text-muted-foreground border-muted-foreground/30',
    features: [
      'Browse all 50 states + international tours',
      'View tour details, stops, maps, and text',
      'Device Narration',
      'Save favorites',
      'Toolkit: 4 tools (2 ad-gated)',
      'Evidence Journal + Dashboard',
    ],
  },
  seeker: {
    id: 'seeker',
    name: 'Seeker',
    manifestation_energy: 0,
    narration_energy: 0,
    monthly_price: 3.99,
    annual_price: 39.99,
    color: 'text-emerald-400',
    badge: 'bg-emerald-500/20 text-emerald-400 border-emerald-500/40',
    features: [
      'Everything in Observer',
      'Ad-Free experience',
      'Toolkit: 4 tools (no ads)',
      'Community Map posting',
      'Evidence saves: 10/day (no ad)',
    ],
  },
  technician: {
    id: 'technician',
    name: 'Technician',
    manifestation_energy: 0,
    narration_energy: 0,
    monthly_price: 5.99,
    annual_price: 59.99,
    color: 'text-sky-400',
    badge: 'bg-sky-500/20 text-sky-400 border-sky-500/40',
    features: [
      'Everything in Seeker',
      'Toolkit: 10 of 12 tools',
      'Aura Bundle access (100% Save Energy)',
      'Evidence saves: 20/day, then Aura',
    ],
  },
  explorer: {
    id: 'explorer',
    name: 'Explorer',
    manifestation_energy: 5,
    narration_energy: 500,
    monthly_price: 7.99,
    annual_price: 79.99,
    color: 'text-primary',
    badge: 'bg-primary/20 text-primary border-primary/40',
    features: [
      'Everything in Observer',
      'Ad-Free tours',
      'AI narration (~1 fully narrated tour/month)',
      'Custom tour generation (1-2/month)',
      'All ranked tours unlocked',
      'Nearby + Abroad tours',
      'Toolkit: 10 of 12 tools',
      'Evidence Journal (upload + track)',
      'Community Map access',
      'Leaderboard access',
      'Aura Bundle purchases',
    ],
  },
  investigator: {
    id: 'investigator',
    name: 'Investigator',
    manifestation_energy: 15,
    narration_energy: 1500,
    monthly_price: 11.99,
    annual_price: 119.99,
    color: 'text-accent-foreground',
    badge: 'bg-accent/20 text-accent-foreground border-accent/40',
    features: [
      'Everything in Explorer',
      'AI narration for ~3 fully narrated tours/month',
      'Custom tour generation (up to 5/month)',
      'Toolkit: All 12 tools',
      'Evidence Dashboard with analytics',
      'Aura Bundle purchases',
    ],
  },
  trailblazer: {
    id: 'trailblazer',
    name: 'Trailblazer',
    manifestation_energy: 15,
    narration_energy: 1500,
    one_time_price: 239.99,
    duration_months: 30,
    max_slots: 300,
    color: 'text-amber-400',
    badge: 'bg-amber-500/20 text-amber-400 border-amber-500/40',
    features: [
      'Everything in Investigator',
      'AI narration for ~3 fully narrated tours/month',
      'Custom tour generation (up to 5/month)',
      'Exclusive Trailblazer badge',
      'Early access to new features',
      '30-month price lock (6 months free)',
      'Seasonal Aura Bundle discounts (20% off)',
      'Limited to 300 slots',
    ],
  },
};

export const AURA_BUNDLES = {
  flicker: {
    id: 'flicker',
    name: 'Flicker',
    energy: 150,
    price: 2.99,
    narration_pct: 0.8,
    manifestation_pct: 0.2,
    icon: '🕯️',
    desc: 'A small spark — 150 energy to top up',
  },
  apparition: {
    id: 'apparition',
    name: 'Apparition',
    energy: 500,
    price: 6.49,
    narration_pct: 0.8,
    manifestation_pct: 0.2,
    icon: '👻',
    desc: 'A steady presence — 500 energy',
  },
  haunting: {
    id: 'haunting',
    name: 'Haunting',
    energy: 1500,
    price: 16.99,
    narration_pct: 0.8,
    manifestation_pct: 0.2,
    icon: '🌫️',
    desc: 'A powerful surge — 1,500 energy',
  },
  spectral: {
    id: 'spectral',
    name: 'Spectral',
    energy: 2500,
    price: 24.99,
    narration_pct: 0.8,
    manifestation_pct: 0.2,
    icon: '✨',
    desc: 'Maximum energy — 2,500 energy',
  },
};

export const PLAN_ORDER = ['observer', 'seeker', 'technician', 'explorer', 'investigator', 'trailblazer'];